package mt

const KER_MATRIX_LOG = `
//
// Generated by NVIDIA NVVM Compiler
// Compiler built on Thu Mar 13 19:31:35 2014 (1394735495)
// Cuda compilation tools, release 6.0, V6.0.1
//

.version 4.0
.target sm_30
.address_size 64


.visible .entry matrixLog(
	.param .u64 matrixLog_param_0,
	.param .u32 matrixLog_param_1,
	.param .u32 matrixLog_param_2,
	.param .u32 matrixLog_param_3,
	.param .u32 matrixLog_param_4
)
{
	.reg .pred 	%p<12>;
	.reg .s32 	%r<35>;
	.reg .f32 	%f<5>;
	.reg .s64 	%rd<5>;
	.reg .f64 	%fd<56>;


	ld.param.u64 	%rd2, [matrixLog_param_0];
	ld.param.u32 	%r12, [matrixLog_param_1];
	ld.param.u32 	%r13, [matrixLog_param_2];
	ld.param.u32 	%r14, [matrixLog_param_3];
	ld.param.u32 	%r15, [matrixLog_param_4];
	mov.u32 	%r16, %ctaid.x;
	mov.u32 	%r17, %tid.x;
	mad.lo.s32 	%r18, %r16, %r12, %r17;
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %tid.y;
	mad.lo.s32 	%r21, %r19, %r13, %r20;
	mad.lo.s32 	%r1, %r21, %r14, %r18;
	setp.lt.s32	%p1, %r1, %r15;
	setp.lt.s32	%p2, %r18, %r14;
	and.pred  	%p3, %p1, %p2;
	@!%p3 bra 	BB0_14;
	bra.uni 	BB0_1;

BB0_1:
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r1, 8;
	add.s64 	%rd1, %rd3, %rd4;
	ld.global.f64 	%fd1, [%rd1];
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r31}, %fd1;
	}
	setp.gt.f64	%p4, %fd1, 0d0000000000000000;
	setp.lt.f64	%p5, %fd1, 0d7FF0000000000000;
	and.pred  	%p6, %p4, %p5;
	@%p6 bra 	BB0_7;

	abs.f64 	%fd9, %fd1;
	setp.gtu.f64	%p7, %fd9, 0d7FF0000000000000;
	@%p7 bra 	BB0_6;

	setp.neu.f64	%p8, %fd1, 0d0000000000000000;
	@%p8 bra 	BB0_5;

	mov.f64 	%fd55, 0dFFF0000000000000;
	bra.uni 	BB0_13;

BB0_5:
	setp.eq.f64	%p9, %fd1, 0d7FF0000000000000;
	selp.f64	%fd55, %fd1, 0dFFF8000000000000, %p9;
	bra.uni 	BB0_13;

BB0_6:
	add.rn.f64 	%fd55, %fd1, %fd1;
	bra.uni 	BB0_13;

BB0_7:
	{
	.reg .b32 %temp; 
	mov.b64 	{%r32, %temp}, %fd1;
	}
	setp.lt.u32	%p10, %r31, 1048576;
	@%p10 bra 	BB0_9;

	mov.u32 	%r33, -1023;
	bra.uni 	BB0_10;

BB0_9:
	mul.rn.f64 	%fd11, %fd1, 0d4350000000000000;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r31}, %fd11;
	}
	{
	.reg .b32 %temp; 
	mov.b64 	{%r32, %temp}, %fd11;
	}
	mov.u32 	%r33, -1077;

BB0_10:
	shr.s32 	%r24, %r31, 20;
	add.s32 	%r34, %r33, %r24;
	and.b32  	%r25, %r31, -2146435073;
	or.b32  	%r26, %r25, 1072693248;
	mov.b64 	%fd54, {%r32, %r26};
	setp.lt.u32	%p11, %r26, 1073127583;
	@%p11 bra 	BB0_12;

	{
	.reg .b32 %temp; 
	mov.b64 	{%r27, %temp}, %fd54;
	}
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r28}, %fd54;
	}
	add.s32 	%r29, %r28, -1048576;
	mov.b64 	%fd54, {%r27, %r29};
	add.s32 	%r34, %r34, 1;

BB0_12:
	add.rn.f64 	%fd12, %fd54, 0d3FF0000000000000;
	mov.f64 	%fd14, 0d3FF0000000000000;
	// inline asm
	cvt.rn.f32.f64     %f1,%fd12;
	// inline asm
	// inline asm
	rcp.approx.ftz.f32 %f2,%f1;
	// inline asm
	// inline asm
	cvt.f64.f32        %fd13,%f2;
	// inline asm
	neg.f64 	%fd15, %fd12;
	fma.rn.f64 	%fd16, %fd15, %fd13, %fd14;
	fma.rn.f64 	%fd17, %fd16, %fd16, %fd16;
	fma.rn.f64 	%fd18, %fd17, %fd13, %fd13;
	add.rn.f64 	%fd19, %fd54, 0dBFF0000000000000;
	mul.rn.f64 	%fd20, %fd19, %fd18;
	add.rn.f64 	%fd21, %fd20, %fd20;
	mul.rn.f64 	%fd22, %fd21, %fd21;
	mov.f64 	%fd23, 0d3ED0EE258B7A8B04;
	mov.f64 	%fd24, 0d3EB1380B3AE80F1E;
	fma.rn.f64 	%fd25, %fd24, %fd22, %fd23;
	mov.f64 	%fd26, 0d3EF3B2669F02676F;
	fma.rn.f64 	%fd27, %fd25, %fd22, %fd26;
	mov.f64 	%fd28, 0d3F1745CBA9AB0956;
	fma.rn.f64 	%fd29, %fd27, %fd22, %fd28;
	mov.f64 	%fd30, 0d3F3C71C72D1B5154;
	fma.rn.f64 	%fd31, %fd29, %fd22, %fd30;
	mov.f64 	%fd32, 0d3F624924923BE72D;
	fma.rn.f64 	%fd33, %fd31, %fd22, %fd32;
	mov.f64 	%fd34, 0d3F8999999999A3C4;
	fma.rn.f64 	%fd35, %fd33, %fd22, %fd34;
	mov.f64 	%fd36, 0d3FB5555555555554;
	fma.rn.f64 	%fd37, %fd35, %fd22, %fd36;
	sub.rn.f64 	%fd38, %fd19, %fd21;
	add.rn.f64 	%fd39, %fd38, %fd38;
	neg.f64 	%fd40, %fd21;
	fma.rn.f64 	%fd41, %fd40, %fd19, %fd39;
	mul.rn.f64 	%fd42, %fd18, %fd41;
	mul.rn.f64 	%fd43, %fd37, %fd22;
	fma.rn.f64 	%fd44, %fd43, %fd21, %fd42;
	cvt.rn.f64.s32	%fd45, %r34;
	mov.f64 	%fd46, 0d3FE62E42FEFA39EF;
	fma.rn.f64 	%fd47, %fd45, %fd46, %fd21;
	neg.s32 	%r30, %r34;
	cvt.rn.f64.s32	%fd48, %r30;
	fma.rn.f64 	%fd49, %fd48, %fd46, %fd47;
	sub.rn.f64 	%fd50, %fd49, %fd21;
	sub.rn.f64 	%fd51, %fd44, %fd50;
	mov.f64 	%fd52, 0d3C7ABC9E3B39803F;
	fma.rn.f64 	%fd53, %fd45, %fd52, %fd51;
	add.rn.f64 	%fd55, %fd47, %fd53;

BB0_13:
	st.global.f64 	[%rd1], %fd55;

BB0_14:
	ret;
}


`
